### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by otrapersona** [p0t4t0sandwich/LPPronouns#1]
is it supposed to come out with this format when I send a message?:

`<MynameMypronouns (Mypronounsagain)> Message`

I mean, the pronouns are there twice.

Edit: I noticed that %displayname% shows MynameMypronouns
and %player% just shows my name however it doesn't show the color (i'm admin/owner)

**Comment by p0t4t0sandwich** [comment]
If you're talking about the colored name from EssentialsX, LP Pronouns doesn't have any integrations for that currently (Something I could look at in the near future though).
If you're using something else for the colors, would you mind showing how it's intended to look along with any configs?
I just want to figure out if there's anything I can do on my end to fix, or if it's just some weird mixup between plugins.

**Comment by otrapersona** [comment]
I'm sorry, I forgot I have other plugins, indeed I'm using EssentialsX and EssentialsXChat. That might be the source of my formatting issues.
