### ISSUE TITLE
crashes on loading with blueprint in 1.19.2

### ISSUE THREAD

**Issue by superdude808** [p0t4t0sandwich/LPPronouns#2]
as in tittle 
crashes with blue print 
net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: LPPronouns:texts/blueprint/splashes.json

[crash-2023-10-20_19.52.55-client.txt](https://github.com/p0t4t0sandwich/LPPronouns/files/13054455/crash-2023-10-20_19.52.55-client.txt)

**Comment by p0t4t0sandwich** [comment]
LPPronouns is a server-side-only mod, since it needs LuckPerms to function
